### PR TITLE
[PR] relations broken

### LINKED ISSUE #129: [BUG] Relations broken
**Description of the bug**
relations are broken

### PR DESCRIPTION
**Pull request by mathisfchx**
### Description
Relations where broken due to the new List feature on the app
Add Edit and Delete features for relations are now working.

### CODE REVIEW

File: Netw4ppl/app/src/main/java/netw4ppl/ines/utils/AdapterViewFields.java [hunk 1]
```diff
@@ -329,7 +329,7 @@ public RecyclerView.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int
     @Override
     public void onBindViewHolder(@NonNull RecyclerView.ViewHolder holder, int position) {
         Field field = mFields.get(position);
-
+        System.out.println("field = " + field.getViewType());
```
Comment (lduf) [inline Netw4ppl/app/src/main/java/netw4ppl/ines/utils/AdapterViewFields.java]:
```suggestion
```

File: Netw4ppl/app/src/main/java/netw4ppl/ines/utils/Field.java [hunk 2]
```diff
@@ -29,6 +31,7 @@ public Field() {
      */
     public Field(String key, String string_fields) throws JSONException {
         super(key, string_fields);
+        System.out.println("Field: " + this.getString("android_type"));
```
Comment (lduf) [inline Netw4ppl/app/src/main/java/netw4ppl/ines/utils/Field.java]:
```suggestion
```

File: Netw4ppl/app/src/main/java/netw4ppl/ines/utils/PersonListAdapter.java [hunk 3]
```diff
@@ -231,4 +257,13 @@ public Person getItem(int position) {
     public long getItemId(int position) {
         return position;
     }
+
+    /**
+     * Clear function for ArrayLists
+     *
+     */
+    public void clear(ArrayList<String> list) {
```
Comment (lduf) [inline Netw4ppl/app/src/main/java/netw4ppl/ines/utils/PersonListAdapter.java]: Clear this useless function

File: Netw4ppl/app/src/main/java/netw4ppl/ines/utils/RelationListAdapter.java [hunk 4]
```diff
@@ -33,10 +33,8 @@ public class RelationListAdapter extends ArrayAdapter<Relation> {
      * A basic ViewHolder to put informations like the two fullnames and Unique IDs and the relation type
      */
     private static class ViewHolder {
-        TextView mFullName1;
-        TextView mFullName2;
-        TextView mUniqueID1;
-        TextView mUniqueID2;
+        TextView mBestDescriptiveValue1;
```
Comment (lduf) [inline Netw4ppl/app/src/main/java/netw4ppl/ines/utils/RelationListAdapter.java]: better if named From / To

File: Netw4ppl/app/src/main/res/layout/activity_add_relation.xml [hunk 5]
```diff
@@ -60,8 +60,7 @@
             <Spinner
                 android:id="@+id/add_relation_type"
                 android:layout_width="match_parent"
-                android:layout_height="match_parent">
-            </Spinner>
+                android:layout_height="match_parent"></Spinner>
```
Comment (lduf) [inline Netw4ppl/app/src/main/res/layout/activity_add_relation.xml]:
```suggestion
                android:layout_height="match_parent">
            </Spinner>
```

**Review by lduf — CHANGES_REQUESTED** [review]

**Review by lduf — APPROVED** [review]
🌍
